
## Last changed: 2026-04-19 10:57:37 UTC
version 14.1R4.8;
system {
    host-name CE2;
    root-authentication {
        encrypted-password "$1$VB5rIE1t$B2kxXov3R8QkU2yLVn5Ys.";
    }
    login {
        user deb {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$1$MRVIIM8.$saCdYQp.Z4w2lSAlwRZ5u1";
            }
        }
    }
    services {
        ssh;
        netconf {
            ssh;
        }
    }
    syslog {
        user * {
            any emergency;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
}
interfaces {
    ge-0/0/1 {
        description PE2;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 10 {
            description L3VPN;
            vlan-id 10;
            family inet {
                address 172.16.0.14/30;
            }
        }
    }
    ge-0/0/3 {
        description PE1;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 10 {
            description L3VPN;
            vlan-id 10;
            family inet {
                address 172.16.0.6/30;
            }
        }
    }
    em0 {
        unit 0 {
            family inet {
                address 192.168.0.160/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 12.12.12.12/32;
            }
        }
    }
}
routing-options {
    autonomous-system 1000;
}
protocols {
    bgp {
        group PE {
            type external;
            family inet {
                unicast;
            }
            export CE2;
            neighbor 172.16.0.5 {
                peer-as 65000;
            }
            neighbor 172.16.0.13 {
                peer-as 65000;
            }
        }
    }
}
policy-options {
    prefix-list CE2_Routes {
        12.12.12.12/32;
    }
    policy-statement CE2 {
        term 10 {
            from {
                prefix-list CE2_Routes;
            }
            then accept;
        }
    }
}
