
## Last changed: 2026-04-06 18:35:24 UTC
version 14.1R4.8;
system {
    host-name CE3;
    root-authentication {
        encrypted-password "$1$4KlIkJR7$JU95zQLF2xdfOnYieb1PT.";
    }
    login {
        user deb {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$1$fXeSNvLs$X1p4cl9JBdLWYgt4myLKC/";
            }
        }
    }
    services {
        ssh;
        netconf {
            ssh;
        }
    }
    syslog {
        user * {
            any emergency;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
}
interfaces {
    ge-0/0/1 {
        description PE3;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 10 {
            description L3VPN;
            vlan-id 10;
            family inet {
                address 172.16.0.18/30;
            }
        }
    }
    ge-0/0/2 {
        description PE4;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 10 {
            description L3VPN;
            vlan-id 10;
            family inet {
                address 172.16.0.26/30;
            }
        }
    }
    em0 {
        unit 0 {
            family inet {
                address 192.168.0.161/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 13.13.13.13/32;
            }
        }
    }
}
routing-options {
    autonomous-system 1001;
}
protocols {
    bgp {
        group PE {
            type external;
            family inet {
                unicast;
            }
            export CE3;
            neighbor 172.16.0.17 {
                peer-as 65000;
            }
            neighbor 172.16.0.25 {
                peer-as 65000;
            }
        }
    }
}
policy-options {
    prefix-list CE3_Routes {
        13.13.13.13/32;
    }
    policy-statement CE3 {
        term 10 {
            from {
                prefix-list CE3_Routes;
            }
            then accept;
        }
    }
}
