
## Last changed: 2026-04-06 18:37:21 UTC
version 14.1R4.8;
system {
    host-name CE4;
    root-authentication {
        encrypted-password "$1$7Jc7TmUN$bdsWqWJjXtAAvzEd6a41h1";
    }
    login {
        user deb {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$1$gx.p8Qzp$aa6hwIpAIKoC3gOAPTj1k/";
            }
        }
    }
    services {
        ssh;
        netconf {
            ssh;
        }
    }
    syslog {
        user * {
            any emergency;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
}
interfaces {
    ge-0/0/0 {
        description PE4;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 10 {
            description L3VPN;
            vlan-id 10;
            family inet {
                address 172.16.0.30/30;
            }
        }
    }
    ge-0/0/3 {
        description PE3;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 10 {
            description L3VPN;
            vlan-id 10;
            family inet {
                address 172.16.0.22/30;
            }
        }
    }
    em0 {
        unit 0 {
            family inet {
                address 192.168.0.162/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 14.14.14.14/32;
            }
        }
    }
}
routing-options {
    autonomous-system 1001;
}
protocols {
    bgp {
        group PE {
            type external;
            family inet {
                unicast;
            }
            export CE4;
            neighbor 172.16.0.29 {
                peer-as 65000;
            }
            neighbor 172.16.0.21 {
                peer-as 65000;
            }
        }
    }
}
policy-options {
    prefix-list CE4_Routes {
        14.14.14.14/32;
    }
    policy-statement CE4 {
        term 10 {
            from {
                prefix-list CE4_Routes;
            }
            then accept;
        }
    }
}
