
set version 21.4R3.15
set system host-name P1
set system root-authentication encrypted-password "$6$pz.Lyj4D$jnHjHpf6klA1hVMY/9s.9z70fjoCmjCwQ9OAU0.J6nb57R4ETmU3CgygwKpGY2mCQG6W3aBrwe2HrO5sMFtjV1"
set system login user deb uid 2000
set system login user deb class super-user
set system login user deb authentication encrypted-password "$6$HrbNTzvf$ezNmjownbbSL.CkpLF.4lSlboaEIDVxW.hDGgUCaFJuIRllnNFYB1nU4JSsWeRwUNJYC80F/4y2NMjg5Lp8tN0"
set system services netconf ssh
set system syslog file interactive-commands interactive-commands any
set system syslog file messages any notice
set system syslog file messages authorization info
set system processes dhcp-service traceoptions file dhcp_logfile
set system processes dhcp-service traceoptions file size 10m
set system processes dhcp-service traceoptions level all
set system processes dhcp-service traceoptions flag packet
set interfaces ge-0/0/0 unit 0 family inet address 10.1.0.10/31
set interfaces ge-0/0/0 unit 0 family iso
set interfaces ge-0/0/0 unit 0 family mpls
set interfaces ge-0/0/1 unit 0 family inet address 10.1.0.1/31
set interfaces ge-0/0/1 unit 0 family iso
set interfaces ge-0/0/1 unit 0 family mpls
set interfaces ge-0/0/2 unit 0 family inet address 10.1.0.19/31
set interfaces ge-0/0/2 unit 0 family iso
set interfaces ge-0/0/2 unit 0 family mpls
set interfaces ge-0/0/3 unit 0 family inet address 10.1.0.12/31
set interfaces ge-0/0/3 unit 0 family iso
set interfaces ge-0/0/3 unit 0 family mpls
set interfaces fxp0 unit 0 family inet address 192.168.0.152/24
set interfaces lo0 unit 0 family inet address 1.1.1.3/32
set interfaces lo0 unit 0 family iso address 49.0001.0000.0000.0003.00
set policy-options policy-statement PL-LB then load-balance per-packet
set routing-options router-id 1.1.1.3
set routing-options autonomous-system 65000
set routing-options forwarding-table export PL-LB
set protocols router-advertisement interface fxp0.0 managed-configuration
set protocols isis interface ge-0/0/0.0 point-to-point
set protocols isis interface ge-0/0/1.0 point-to-point
set protocols isis interface ge-0/0/2.0 point-to-point
set protocols isis interface ge-0/0/3.0 point-to-point
set protocols isis interface lo0.0 passive
set protocols isis level 1 disable
set protocols isis level 2 wide-metrics-only
set protocols ldp track-igp-metric
set protocols ldp interface ge-0/0/0.0
set protocols ldp interface ge-0/0/1.0
set protocols ldp interface ge-0/0/2.0
set protocols ldp interface ge-0/0/3.0
set protocols mpls icmp-tunneling
set protocols mpls interface ge-0/0/1.0
set protocols mpls interface ge-0/0/0.0
set protocols mpls interface ge-0/0/3.0
set protocols mpls interface ge-0/0/2.0
