
## Last changed: 2026-04-06 11:23:12 UTC
version 21.4R3.15;
system {
    host-name P1;
    root-authentication {
        encrypted-password "$6$pz.Lyj4D$jnHjHpf6klA1hVMY/9s.9z70fjoCmjCwQ9OAU0.J6nb57R4ETmU3CgygwKpGY2mCQG6W3aBrwe2HrO5sMFtjV1";
    }
    login {
        user deb {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$HrbNTzvf$ezNmjownbbSL.CkpLF.4lSlboaEIDVxW.hDGgUCaFJuIRllnNFYB1nU4JSsWeRwUNJYC80F/4y2NMjg5Lp8tN0";
            }
        }
    }
    services {
        netconf {
            ssh;
        }
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
    processes {
        dhcp-service {
            traceoptions {
                file dhcp_logfile size 10m;
                level all;
                flag packet;
            }
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.1.0.10/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.1.0.1/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 10.1.0.19/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/3 {
        unit 0 {
            family inet {
                address 10.1.0.12/31;
            }
            family iso;
            family mpls;
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 192.168.0.152/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.3/32;
            }
            family iso {
                address 49.0001.0000.0000.0003.00;
            }
        }
    }
}
policy-options {
    policy-statement PL-LB {
        then {
            load-balance per-packet;
        }
    }
}
routing-options {
    router-id 1.1.1.3;
    autonomous-system 65000;
    forwarding-table {
        export PL-LB;
    }
}
protocols {
    router-advertisement {
        interface fxp0.0 {
            managed-configuration;
        }
    }
    isis {
        interface ge-0/0/0.0 {
            point-to-point;
        }
        interface ge-0/0/1.0 {
            point-to-point;
        }
        interface ge-0/0/2.0 {
            point-to-point;
        }
        interface ge-0/0/3.0 {
            point-to-point;
        }
        interface lo0.0 {
            passive;
        }
        level 1 disable;
        level 2 wide-metrics-only;
    }
    ldp {
        track-igp-metric;
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
        interface ge-0/0/2.0;
        interface ge-0/0/3.0;
    }
    mpls {
        icmp-tunneling;
        interface ge-0/0/1.0;
        interface ge-0/0/0.0;
        interface ge-0/0/3.0;
        interface ge-0/0/2.0;
    }
}
