
## Last changed: 2026-04-06 11:23:07 UTC
version 21.4R3.15;
system {
    host-name P2;
    root-authentication {
        encrypted-password "$6$akiCdjlt$u.lFqSdu3q.Df.aVYjef.1yQBRGl8Q1Y98NjOFmOiEZdlhPYq3ZM23vCX87HEfvUfWSJpH0FUIhPec/1tOzqm0";
    }
    login {
        user deb {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$Kd/xuIeA$GWwMQF/uM6usSsMyBH4LMf4i4o1k2TEqWg5snKMUyHO89Bpsow8ovLOn5LlcX0zxR3By59N10Ib69lbn6b2Y70";
            }
        }
    }
    services {
        netconf {
            ssh;
        }
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
    processes {
        dhcp-service {
            traceoptions {
                file dhcp_logfile size 10m;
                level all;
                flag packet;
            }
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.1.0.16/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.1.0.14/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 10.1.0.7/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/3 {
        unit 0 {
            family inet {
                address 10.1.0.23/31;
            }
            family iso;
            family mpls;
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 192.168.0.156/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.4/32;
            }
            family iso {
                address 49.0001.0000.0000.0004.00;
            }
        }
    }
}
policy-options {
    policy-statement PL-LB {
        then {
            load-balance per-packet;
        }
    }
}
routing-options {
    router-id 1.1.1.4;
    autonomous-system 65000;
    forwarding-table {
        export PL-LB;
    }
}
protocols {
    isis {
        interface ge-0/0/0.0 {
            point-to-point;
        }
        interface ge-0/0/1.0 {
            point-to-point;
        }
        interface ge-0/0/2.0 {
            point-to-point;
        }
        interface ge-0/0/3.0 {
            point-to-point;
        }
        interface lo0.0 {
            passive;
        }
        level 1 disable;
        level 2 wide-metrics-only;
    }
    ldp {
        track-igp-metric;
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
        interface ge-0/0/2.0;
        interface ge-0/0/3.0;
    }
    mpls {
        interface ge-0/0/2.0;
        interface ge-0/0/1.0;
        interface ge-0/0/0.0;
        interface ge-0/0/3.0;
    }
}
