
set version 21.4R3.15
set system host-name P2
set system root-authentication encrypted-password "$6$akiCdjlt$u.lFqSdu3q.Df.aVYjef.1yQBRGl8Q1Y98NjOFmOiEZdlhPYq3ZM23vCX87HEfvUfWSJpH0FUIhPec/1tOzqm0"
set system login user deb uid 2000
set system login user deb class super-user
set system login user deb authentication encrypted-password "$6$Kd/xuIeA$GWwMQF/uM6usSsMyBH4LMf4i4o1k2TEqWg5snKMUyHO89Bpsow8ovLOn5LlcX0zxR3By59N10Ib69lbn6b2Y70"
set system services netconf ssh
set system syslog file interactive-commands interactive-commands any
set system syslog file messages any notice
set system syslog file messages authorization info
set system processes dhcp-service traceoptions file dhcp_logfile
set system processes dhcp-service traceoptions file size 10m
set system processes dhcp-service traceoptions level all
set system processes dhcp-service traceoptions flag packet
set interfaces ge-0/0/0 unit 0 family inet address 10.1.0.16/31
set interfaces ge-0/0/0 unit 0 family iso
set interfaces ge-0/0/0 unit 0 family mpls
set interfaces ge-0/0/1 unit 0 family inet address 10.1.0.14/31
set interfaces ge-0/0/1 unit 0 family iso
set interfaces ge-0/0/1 unit 0 family mpls
set interfaces ge-0/0/2 unit 0 family inet address 10.1.0.7/31
set interfaces ge-0/0/2 unit 0 family iso
set interfaces ge-0/0/2 unit 0 family mpls
set interfaces ge-0/0/3 unit 0 family inet address 10.1.0.23/31
set interfaces ge-0/0/3 unit 0 family iso
set interfaces ge-0/0/3 unit 0 family mpls
set interfaces fxp0 unit 0 family inet address 192.168.0.156/24
set interfaces lo0 unit 0 family inet address 1.1.1.4/32
set interfaces lo0 unit 0 family iso address 49.0001.0000.0000.0004.00
set policy-options policy-statement PL-LB then load-balance per-packet
set routing-options router-id 1.1.1.4
set routing-options autonomous-system 65000
set routing-options forwarding-table export PL-LB
set protocols isis interface ge-0/0/0.0 point-to-point
set protocols isis interface ge-0/0/1.0 point-to-point
set protocols isis interface ge-0/0/2.0 point-to-point
set protocols isis interface ge-0/0/3.0 point-to-point
set protocols isis interface lo0.0 passive
set protocols isis level 1 disable
set protocols isis level 2 wide-metrics-only
set protocols ldp track-igp-metric
set protocols ldp interface ge-0/0/0.0
set protocols ldp interface ge-0/0/1.0
set protocols ldp interface ge-0/0/2.0
set protocols ldp interface ge-0/0/3.0
set protocols mpls interface ge-0/0/2.0
set protocols mpls interface ge-0/0/1.0
set protocols mpls interface ge-0/0/0.0
set protocols mpls interface ge-0/0/3.0
