
set version 21.4R3.15
set system host-name PE1
set system root-authentication encrypted-password "$6$y4q6DIHF$iJui8GoY38/pWtdhhfHjMCiPaNM7EvGNNLcf6wq4D6j4QbrKtpyLlwP3PpgbBcHsB8h1M2/BkryjpjV6vHvs3/"
set system login user deb uid 2000
set system login user deb class super-user
set system login user deb authentication encrypted-password "$6$ku10IpcQ$IhnlRU47X4ETQgHx3RHx8tCHG/TiZZ4zBcZBf/g0QXhT54vyZLwJqsLH5zs8Ftu5mqmmKOZ7XAuWXbK1ZimP00"
set system services netconf ssh
set system syslog file interactive-commands interactive-commands any
set system syslog file messages any notice
set system syslog file messages authorization info
set system processes dhcp-service traceoptions file dhcp_logfile
set system processes dhcp-service traceoptions file size 10m
set system processes dhcp-service traceoptions level all
set system processes dhcp-service traceoptions flag packet
set interfaces ge-0/0/0 unit 0 family inet address 10.1.0.2/31
set interfaces ge-0/0/0 unit 0 family iso
set interfaces ge-0/0/0 unit 0 family mpls
set interfaces ge-0/0/1 unit 0 family inet address 10.1.0.0/31
set interfaces ge-0/0/1 unit 0 family iso
set interfaces ge-0/0/1 unit 0 family mpls
set interfaces ge-0/0/2 description CE-1
set interfaces ge-0/0/2 flexible-vlan-tagging
set interfaces ge-0/0/2 encapsulation flexible-ethernet-services
set interfaces ge-0/0/2 unit 10 description L3VPN
set interfaces ge-0/0/2 unit 10 vlan-id 10
set interfaces ge-0/0/2 unit 10 family inet address 172.16.0.1/30
set interfaces ge-0/0/3 description CE2
set interfaces ge-0/0/3 flexible-vlan-tagging
set interfaces ge-0/0/3 encapsulation flexible-ethernet-services
set interfaces ge-0/0/3 unit 10 description L3VPN
set interfaces ge-0/0/3 unit 10 vlan-id 10
set interfaces ge-0/0/3 unit 10 family inet address 172.16.0.5/30
set interfaces ge-0/0/4 unit 0 family inet address 10.1.0.4/31
set interfaces ge-0/0/4 unit 0 family iso
set interfaces ge-0/0/4 unit 0 family mpls
set interfaces fxp0 unit 0 family inet address 192.168.0.151/24
set interfaces lo0 unit 0 family inet address 1.1.1.1/32
set interfaces lo0 unit 0 family iso address 49.0001.0000.0000.0001.00
set policy-options policy-statement NHS then next-hop self
set policy-options policy-statement PL-LB then load-balance per-packet
set routing-options router-id 1.1.1.1
set routing-options autonomous-system 65000
set routing-options forwarding-table export PL-LB
set protocols bgp group AS_65000 type internal
set protocols bgp group AS_65000 local-address 1.1.1.1
set protocols bgp group AS_65000 family inet unicast
set protocols bgp group AS_65000 family inet-vpn unicast
set protocols bgp group AS_65000 family inet6-vpn unicast
set protocols bgp group AS_65000 export NHS
set protocols bgp group AS_65000 neighbor 1.1.1.5
set protocols bgp group AS_65000 neighbor 1.1.1.6
set protocols bgp group CE type external
set protocols bgp group CE family inet unicast
set protocols bgp group CE neighbor 172.16.0.2 peer-as 1000
set protocols bgp group CE neighbor 172.16.0.6 peer-as 1000
set protocols isis interface ge-0/0/0.0 ldp-synchronization
set protocols isis interface ge-0/0/0.0 point-to-point
set protocols isis interface ge-0/0/1.0 ldp-synchronization
set protocols isis interface ge-0/0/1.0 point-to-point
set protocols isis interface ge-0/0/4.0 ldp-synchronization
set protocols isis interface ge-0/0/4.0 point-to-point
set protocols isis interface lo0.0 passive
set protocols isis level 1 disable
set protocols isis level 2 wide-metrics-only
set protocols ldp track-igp-metric
set protocols ldp interface ge-0/0/0.0
set protocols ldp interface ge-0/0/1.0
set protocols ldp interface ge-0/0/2.0
set protocols ldp interface ge-0/0/3.0
set protocols ldp interface ge-0/0/4.0
set protocols mpls icmp-tunneling
set protocols mpls interface ge-0/0/1.0
set protocols mpls interface ge-0/0/0.0
set protocols mpls interface ge-0/0/4.0
set protocols mpls interface ge-0/0/2.0
set protocols mpls interface ge-0/0/3.0
