
set version 21.4R3.15
set system host-name RR1
set system root-authentication encrypted-password "$6$.keKFHYO$oA0aJ1AC1H6VXgDW6Tg0i1EwIMhJMijbnGPCJsQ46x/y5duwiq9KzN2zKHEwHPj4J85TNBprTBBP.xkhp0W6y1"
set system login user deb uid 2000
set system login user deb class super-user
set system login user deb authentication encrypted-password "$6$JCYYXW22$z4RY1zrJvRSIu7KVoMOMAH6x2w3E2FIpvF3VWsE.sIexJBHkenjAWuThbvvwToo.vCQ6mFN39n7rDOkYgi9Y8/"
set system services netconf ssh
set system syslog file interactive-commands interactive-commands any
set system syslog file messages any notice
set system syslog file messages authorization info
set system processes dhcp-service traceoptions file dhcp_logfile
set system processes dhcp-service traceoptions file size 10m
set system processes dhcp-service traceoptions level all
set system processes dhcp-service traceoptions flag packet
set interfaces ge-0/0/0 unit 0 family inet address 10.1.0.11/31
set interfaces ge-0/0/0 unit 0 family iso
set interfaces ge-0/0/0 unit 0 family mpls
set interfaces ge-0/0/1 unit 0 family inet address 10.1.0.15/31
set interfaces ge-0/0/1 unit 0 family iso
set interfaces ge-0/0/1 unit 0 family mpls
set interfaces ge-0/0/4 unit 0 family inet address 10.1.0.5/31
set interfaces ge-0/0/4 unit 0 family iso
set interfaces ge-0/0/4 unit 0 family mpls
set interfaces ge-0/0/5 unit 0 family inet address 10.1.0.9/31
set interfaces ge-0/0/5 unit 0 family iso
set interfaces ge-0/0/5 unit 0 family mpls
set interfaces fxp0 unit 0 family inet address 192.168.0.154/24
set interfaces lo0 unit 0 family inet address 1.1.1.5/32
set interfaces lo0 unit 0 family iso address 49.0001.0000.0000.0005.00
set policy-options policy-statement PL-LB then load-balance per-packet
set routing-options router-id 1.1.1.5
set routing-options autonomous-system 65000
set routing-options forwarding-table export PL-LB
set protocols bgp group IBGP_RR_MESH type internal
set protocols bgp group IBGP_RR_MESH local-address 1.1.1.5
set protocols bgp group IBGP_RR_MESH family inet unicast
set protocols bgp group IBGP_RR_MESH family inet-vpn unicast
set protocols bgp group IBGP_RR_MESH family inet6-vpn unicast
set protocols bgp group IBGP_RR_MESH neighbor 1.1.1.6
set protocols bgp group IBGP_CLIENTS type internal
set protocols bgp group IBGP_CLIENTS local-address 1.1.1.5
set protocols bgp group IBGP_CLIENTS family inet unicast
set protocols bgp group IBGP_CLIENTS family inet-vpn unicast
set protocols bgp group IBGP_CLIENTS family inet6-vpn unicast
set protocols bgp group IBGP_CLIENTS cluster 1.1.1.100
set protocols bgp group IBGP_CLIENTS neighbor 1.1.1.1
set protocols bgp group IBGP_CLIENTS neighbor 1.1.1.2
set protocols bgp group IBGP_CLIENTS neighbor 1.1.1.7
set protocols bgp group IBGP_CLIENTS neighbor 1.1.1.8
set protocols isis interface ge-0/0/0.0 point-to-point
set protocols isis interface ge-0/0/1.0 point-to-point
set protocols isis interface ge-0/0/4.0 point-to-point
set protocols isis interface ge-0/0/5.0 point-to-point
set protocols isis interface lo0.0 passive
set protocols isis level 1 disable
set protocols isis level 2 wide-metrics-only
set protocols ldp track-igp-metric
set protocols ldp interface ge-0/0/0.0
set protocols ldp interface ge-0/0/1.0
set protocols ldp interface ge-0/0/4.0
set protocols ldp interface ge-0/0/5.0
set protocols mpls interface ge-0/0/4.0
set protocols mpls interface ge-0/0/5.0
set protocols mpls interface ge-0/0/0.0
set protocols mpls interface ge-0/0/1.0
