
## Last changed: 2026-04-06 17:11:44 UTC
version 21.4R3.15;
system {
    host-name RR1;
    root-authentication {
        encrypted-password "$6$.keKFHYO$oA0aJ1AC1H6VXgDW6Tg0i1EwIMhJMijbnGPCJsQ46x/y5duwiq9KzN2zKHEwHPj4J85TNBprTBBP.xkhp0W6y1";
    }
    login {
        user deb {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$JCYYXW22$z4RY1zrJvRSIu7KVoMOMAH6x2w3E2FIpvF3VWsE.sIexJBHkenjAWuThbvvwToo.vCQ6mFN39n7rDOkYgi9Y8/";
            }
        }
    }
    services {
        netconf {
            ssh;
        }
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
    processes {
        dhcp-service {
            traceoptions {
                file dhcp_logfile size 10m;
                level all;
                flag packet;
            }
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.1.0.11/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.1.0.15/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/4 {
        unit 0 {
            family inet {
                address 10.1.0.5/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/5 {
        unit 0 {
            family inet {
                address 10.1.0.9/31;
            }
            family iso;
            family mpls;
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 192.168.0.154/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.5/32;
            }
            family iso {
                address 49.0001.0000.0000.0005.00;
            }
        }
    }
}
policy-options {
    policy-statement PL-LB {
        then {
            load-balance per-packet;
        }
    }
}
routing-options {
    router-id 1.1.1.5;
    autonomous-system 65000;
    forwarding-table {
        export PL-LB;
    }
}
protocols {
    bgp {
        group IBGP_RR_MESH {
            type internal;
            local-address 1.1.1.5;
            family inet {
                unicast;
            }
            family inet-vpn {
                unicast;
            }
            family inet6-vpn {
                unicast;
            }
            neighbor 1.1.1.6;
        }
        group IBGP_CLIENTS {
            type internal;
            local-address 1.1.1.5;
            family inet {
                unicast;
            }
            family inet-vpn {
                unicast;
            }
            family inet6-vpn {
                unicast;
            }
            cluster 1.1.1.100;
            neighbor 1.1.1.1;
            neighbor 1.1.1.2;
            neighbor 1.1.1.7;
            neighbor 1.1.1.8;
        }
    }
    isis {
        interface ge-0/0/0.0 {
            point-to-point;
        }
        interface ge-0/0/1.0 {
            point-to-point;
        }
        interface ge-0/0/4.0 {
            point-to-point;
        }
        interface ge-0/0/5.0 {
            point-to-point;
        }
        interface lo0.0 {
            passive;
        }
        level 1 disable;
        level 2 wide-metrics-only;
    }
    ldp {
        track-igp-metric;
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
        interface ge-0/0/4.0;
        interface ge-0/0/5.0;
    }
    mpls {
        interface ge-0/0/4.0;
        interface ge-0/0/5.0;
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
    }
}
