
## Last changed: 2026-04-06 11:23:10 UTC
version 21.4R3.15;
system {
    host-name RR2;
    root-authentication {
        encrypted-password "$6$9Q8W3iOQ$/uIJ56c1F6S5X6W18ZvGyGZr7eefNk.ykzFApTqwYgAo3WB/dCyVjyDPaZTrQPA3qBJ44rUq1v85x/uwI2c.L.";
    }
    login {
        user deb {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$b6fBWJvr$D2rpWIQo5MhrYIWj1VKCGD4BE0h4q2sXHiq5h0/r1DElqiURxaRMEXROszTRChe7ECo3nhh4trdbvNSZpBHa..";
            }
        }
    }
    services {
        ssh;
        netconf {
            ssh;
        }
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
    processes {
        dhcp-service {
            traceoptions {
                file dhcp_logfile size 10m;
                level all;
                flag packet;
            }
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.1.0.17/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/3 {
        unit 0 {
            family inet {
                address 10.1.0.13/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/4 {
        unit 0 {
            family inet {
                address 10.1.0.27/31;
            }
            family iso;
            family mpls;
        }
    }
    ge-0/0/5 {
        unit 0 {
            family inet {
                address 10.1.0.25/31;
            }
            family iso;
            family mpls;
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 192.168.0.158/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.6/32;
            }
            family iso {
                address 49.0001.0000.0000.0006.00;
            }
        }
    }
}
policy-options {
    policy-statement PL-LB {
        then {
            load-balance per-packet;
        }
    }
}
routing-options {
    router-id 1.1.1.6;
    autonomous-system 65000;
    forwarding-table {
        export PL-LB;
    }
}
protocols {
    bgp {
        group IBGP_RR_MESH {
            type internal;
            local-address 1.1.1.6;
            family inet {
                unicast;
            }
            neighbor 1.1.1.5;
        }
        group IBGP_CLIENTS {
            type internal;
            local-address 1.1.1.6;
            family inet {
                unicast;
            }
            cluster 1.1.1.100;
            neighbor 1.1.1.1;
            neighbor 1.1.1.2;
            neighbor 1.1.1.7;
            neighbor 1.1.1.8;
        }
    }
    isis {
        interface ge-0/0/0.0 {
            point-to-point;
        }
        interface ge-0/0/3.0 {
            point-to-point;
        }
        interface ge-0/0/4.0 {
            point-to-point;
        }
        interface ge-0/0/5.0 {
            point-to-point;
        }
        interface lo0.0 {
            passive;
        }
        level 1 disable;
        level 2 wide-metrics-only;
    }
    ldp {
        track-igp-metric;
        interface ge-0/0/0.0;
        interface ge-0/0/3.0;
        interface ge-0/0/4.0;
        interface ge-0/0/5.0;
    }
    mpls {
        interface ge-0/0/3.0;
        interface ge-0/0/0.0;
        interface ge-0/0/5.0;
        interface ge-0/0/4.0;
    }
}
